#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument
#if no argument passed Ping the IP 5 times
ip=$1
if [ "$ip" == "" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$ip"
fi
