#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20
i=1
while ((i <= 20))
do
    echo $i
    case $i in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
    ((i++))
done
