#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes
hour=0
while ((hour < 13))
do
    echo "Hour: $hour"
    min=1
    while ((min < 60))
    do
	echo $min
	((min++))
    done
    ((hour++))
done
